schema_version = "1.0.0"
id = "genai"
version = "3.0.0"
name = "GenAI Mesh Generator"
tagline = "Open-source integrated 3D Mesh Generator for Blender"
maintainer = "Lê Trường Long Hưng <hungltl.18@grad.uit.edu.vn>"
type = "add-on"
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]

# You can specify what platforms this can be used with.
# platforms = ["windows-x64", "windows-arm64", "macos-arm64", "macos-x64" , "linux-x64"]
# NOTE: All wheels for all platforms will be downloaded in you specify `--all-wheels`
# no matter which platforms are specified here.
# NOTE: If `--all-wheels` is specified and the platforms are not specified, it will
# download all the platforms, and generate builds for all platforms.

wheels = [
	"./wheels/absl_py-2.3.1-py3-none-any.whl",
	"./wheels/accelerate-1.10.1-py3-none-any.whl",
	"./wheels/aiofiles-24.1.0-py3-none-any.whl",
	"./wheels/aiohappyeyeballs-2.6.1-py3-none-any.whl",
	"./wheels/aiohttp-3.12.15-cp311-cp311-win_amd64.whl",
	"./wheels/aiosignal-1.4.0-py3-none-any.whl",
	"./wheels/annotated_types-0.7.0-py3-none-any.whl",
	"./wheels/antlr4_python3_runtime-4.9.3-py3-none-any.whl",
	"./wheels/anyio-4.11.0-py3-none-any.whl",
	"./wheels/attrs-25.3.0-py3-none-any.whl",
	"./wheels/bcrypt-5.0.0-cp39-abi3-win_amd64.whl",
	"./wheels/boto3-1.40.45-py3-none-any.whl",
	"./wheels/botocore-1.40.45-py3-none-any.whl",
	"./wheels/Brotli-1.1.0-cp311-cp311-win_amd64.whl",
	"./wheels/certifi-2025.8.3-py3-none-any.whl",
	"./wheels/cffi-2.0.0-cp311-cp311-win_amd64.whl",
	"./wheels/charset_normalizer-3.4.3-cp311-cp311-win_amd64.whl",
	"./wheels/click-8.3.0-py3-none-any.whl",
	"./wheels/colorama-0.4.6-py2.py3-none-any.whl",
	"./wheels/contourpy-1.3.3-cp311-cp311-win_amd64.whl",
	"./wheels/cryptography-46.0.2-cp311-abi3-win_amd64.whl",
	"./wheels/cycler-0.12.1-py3-none-any.whl",
	"./wheels/datasets-4.1.1-py3-none-any.whl",
	"./wheels/diffusers-0.35.1-py3-none-any.whl",
	"./wheels/dill-0.4.0-py3-none-any.whl",
	"./wheels/einops-0.8.1-py3-none-any.whl",
	"./wheels/fastapi-0.118.0-py3-none-any.whl",
	"./wheels/ffmpy-0.6.1-py3-none-any.whl",
	"./wheels/filelock-3.19.1-py3-none-any.whl",
	"./wheels/fonttools-4.60.1-cp311-cp311-win_amd64.whl",
	"./wheels/frozenlist-1.7.0-cp311-cp311-win_amd64.whl",
	"./wheels/fsspec-2025.9.0-py3-none-any.whl",
	"./wheels/gitdb-4.0.12-py3-none-any.whl",
	"./wheels/gitpython-3.1.45-py3-none-any.whl",
	"./wheels/glcontext-3.0.0-cp311-cp311-win_amd64.whl",
	"./wheels/gradio_client-1.13.3-py3-none-any.whl",
	"./wheels/gradio-5.49.0-py3-none-any.whl",
	"./wheels/groovy-0.1.2-py3-none-any.whl",
	"./wheels/grpcio-1.75.1-cp311-cp311-win_amd64.whl",
	"./wheels/h11-0.16.0-py3-none-any.whl",
	"./wheels/httpcore-1.0.9-py3-none-any.whl",
	"./wheels/httpx-0.28.1-py3-none-any.whl",
	"./wheels/huggingface_hub-0.35.3-py3-none-any.whl",
	"./wheels/idna-3.10-py3-none-any.whl",
	"./wheels/imageio_ffmpeg-0.6.0-py3-none-win_amd64.whl",
	"./wheels/imageio-2.37.0-py3-none-any.whl",
	"./wheels/importlib_metadata-8.7.0-py3-none-any.whl",
	"./wheels/jaxtyping-0.3.3-py3-none-any.whl",
	"./wheels/jinja2-3.1.6-py3-none-any.whl",
	"./wheels/jmespath-1.0.1-py3-none-any.whl",
	"./wheels/joblib-1.5.2-py3-none-any.whl",
	"./wheels/kiwisolver-1.4.9-cp311-cp311-win_amd64.whl",
	"./wheels/lazy_loader-0.4-py3-none-any.whl",
	"./wheels/lightning_utilities-0.15.2-py3-none-any.whl",
	"./wheels/lpips-0.1.4-py3-none-any.whl",
	"./wheels/markdown_it_py-4.0.0-py3-none-any.whl",
	"./wheels/markdown-3.9-py3-none-any.whl",
	"./wheels/markupsafe-3.0.3-cp311-cp311-win_amd64.whl",
	"./wheels/matplotlib-3.10.6-cp311-cp311-win_amd64.whl",
	"./wheels/mdurl-0.1.2-py3-none-any.whl",
	"./wheels/megfile-4.2.4-py3-none-any.whl",
	"./wheels/moderngl-5.12.0-cp311-cp311-win_amd64.whl",
	"./wheels/mpmath-1.3.0-py3-none-any.whl",
	"./wheels/multidict-6.6.4-cp311-cp311-win_amd64.whl",
	"./wheels/multiprocess-0.70.16-py311-none-any.whl",
	"./wheels/networkx-3.5-py3-none-any.whl",
	"./wheels/numpy-2.2.6-cp311-cp311-win_amd64.whl",
	"./wheels/omegaconf-2.3.0-py3-none-any.whl",
	"./wheels/opencv_python-4.12.0.88-cp37-abi3-win_amd64.whl",
	"./wheels/optimum-1.27.0-py3-none-any.whl",
	"./wheels/orjson-3.11.3-cp311-cp311-win_amd64.whl",
	"./wheels/packaging-25.0-py3-none-any.whl",
	"./wheels/pandas-2.3.3-cp311-cp311-win_amd64.whl",
	"./wheels/paramiko-3.5.1-py3-none-any.whl",
	"./wheels/pillow-11.3.0-cp311-cp311-win_amd64.whl",
	"./wheels/platformdirs-4.4.0-py3-none-any.whl",
	"./wheels/plyfile-1.1.2-py3-none-any.whl",
	"./wheels/propcache-0.3.2-cp311-cp311-win_amd64.whl",
	"./wheels/protobuf-6.32.1-cp310-abi3-win_amd64.whl",
	"./wheels/psutil-5.9.8-cp37-abi3-win_amd64.whl",
	"./wheels/pyarrow-21.0.0-cp311-cp311-win_amd64.whl",
	"./wheels/pycparser-2.23-py3-none-any.whl",
	"./wheels/pydantic_core-2.33.2-cp311-cp311-win_amd64.whl",
	"./wheels/pydantic-2.11.10-py3-none-any.whl",
	"./wheels/pydub-0.25.1-py2.py3-none-any.whl",
	"./wheels/pygments-2.19.2-py3-none-any.whl",
	"./wheels/PyMCubes-0.1.6-cp311-cp311-win_amd64.whl",
	"./wheels/pynacl-1.6.0-cp38-abi3-win_amd64.whl",
	"./wheels/pyparsing-3.2.5-py3-none-any.whl",
	"./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
	"./wheels/python_multipart-0.0.20-py3-none-any.whl",
	"./wheels/pytorch_lightning-2.5.5-py3-none-any.whl",
	"./wheels/pytz-2025.2-py2.py3-none-any.whl",
	"./wheels/pyyaml-6.0.3-cp311-cp311-win_amd64.whl",
	"./wheels/regex-2025.9.18-cp311-cp311-win_amd64.whl",
	"./wheels/requests-2.32.5-py3-none-any.whl",
	"./wheels/rich-14.1.0-py3-none-any.whl",
	"./wheels/ruff-0.13.3-py3-none-win_amd64.whl",
	"./wheels/s3transfer-0.14.0-py3-none-any.whl",
	"./wheels/safehttpx-0.1.6-py3-none-any.whl",
	"./wheels/safetensors-0.6.2-cp38-abi3-win_amd64.whl",
	"./wheels/scikit_image-0.25.2-cp311-cp311-win_amd64.whl",
	"./wheels/scipy-1.16.2-cp311-cp311-win_amd64.whl",
	"./wheels/semantic_version-2.10.0-py2.py3-none-any.whl",
	"./wheels/sentry_sdk-2.39.0-py2.py3-none-any.whl",
	"./wheels/setuptools-80.9.0-py3-none-any.whl",
	"./wheels/shellingham-1.5.4-py2.py3-none-any.whl",
	"./wheels/six-1.17.0-py2.py3-none-any.whl",
	"./wheels/smmap-5.0.2-py3-none-any.whl",
	"./wheels/sniffio-1.3.1-py3-none-any.whl",
	"./wheels/socksio-1.0.0-py3-none-any.whl",
	"./wheels/spaces-0.42.1-py3-none-any.whl",
	"./wheels/starlette-0.48.0-py3-none-any.whl",
	"./wheels/sympy-1.14.0-py3-none-any.whl",
	"./wheels/tensorboard_data_server-0.7.2-py3-none-any.whl",
	"./wheels/tensorboard-2.20.0-py3-none-any.whl",
	"./wheels/tensorboardx-2.6.4-py3-none-any.whl",
	"./wheels/tifffile-2025.9.30-py3-none-any.whl",
	"./wheels/timm-1.0.20-py3-none-any.whl",
	"./wheels/tokenizers-0.22.1-cp39-abi3-win_amd64.whl",
	"./wheels/tomlkit-0.13.3-py3-none-any.whl",
	"./wheels/torch-2.8.0+cu126-cp311-cp311-win_amd64.whl",
	"./wheels/torch-2.8.0-cp311-cp311-win_amd64.whl",
	"./wheels/torchmcubes-0.1.0-cp311-cp311-win_amd64.whl",
	"./wheels/torchmetrics-1.8.2-py3-none-any.whl",
	"./wheels/torchvision-0.23.0+cu126-cp311-cp311-win_amd64.whl",
	"./wheels/torchvision-0.23.0-cp311-cp311-win_amd64.whl",
	"./wheels/tqdm-4.67.1-py3-none-any.whl",
	"./wheels/transformers-4.57.0-py3-none-any.whl",
	"./wheels/trimesh-4.8.3-py3-none-any.whl",
	"./wheels/typeguard-4.4.4-py3-none-any.whl",
	"./wheels/typer-0.19.2-py3-none-any.whl",
	"./wheels/typing_extensions-4.15.0-py3-none-any.whl",
	"./wheels/typing_inspection-0.4.2-py3-none-any.whl",
	"./wheels/tzdata-2025.2-py2.py3-none-any.whl",
	"./wheels/urllib3-2.5.0-py3-none-any.whl",
	"./wheels/uvicorn-0.37.0-py3-none-any.whl",
	"./wheels/wadler_lindig-0.1.7-py3-none-any.whl",
	"./wheels/wandb-0.22.1-py3-none-win_amd64.whl",
	"./wheels/websockets-15.0.1-cp311-cp311-win_amd64.whl",
	"./wheels/werkzeug-3.1.3-py3-none-any.whl",
	"./wheels/xatlas-0.0.11-cp311-cp311-win_amd64.whl",
	"./wheels/xxhash-3.6.0-cp311-cp311-win_amd64.whl",
	"./wheels/yarl-1.20.1-cp311-cp311-win_amd64.whl",
	"./wheels/zipp-3.23.0-py3-none-any.whl"
]

[permissions]
files = "import/export files"


[build]
# Some optional extra options were added to this table
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "env/",
  "download/",
  "update_wheels.py",
  "wheels.txt",
  "requirements.txt",
  "weights/"
]